name: GitLab mirror

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  repository_mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to GitLab mirror
        env:
          name_token: github-mirroring
          token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          repo: SciBourne/test-task-urlencode-app.git
        run: |
          git clone --bare https://github.com/SciBourne/test-task--urlencode-app.git
          cd test-task--urlencode-app.git          
          git push --mirror https://${name_token}:${token}@gitlab.com/${repo}
